#!/usr/bin/env bash
# Work out border-image-slice values for the sliced Nordic frames.
#
# Each frame is a thin line border with an ornament in the corners (trinity
# knots, nested diamonds). border-image needs to know how far in the ornament
# reaches, or the corners get stretched and smeared across the edge.
#
# Method: collapse the alpha channel to a 1px-tall strip, which gives the mean
# alpha per column. Plain border columns settle to a low steady value (just the
# top and bottom rules); ornament columns are much denser. The ornament ends at
# the last column above the steady-state baseline. Same again vertically.
#
# Output is CSS-ready: one custom property per frame.

set -euo pipefail

IMG_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/src/Rmv.Web/wwwroot/img/ui}"
FRAMES=(panel-frame-card header-bar-frame title-plaque-frame button-frame input-frame)

# The alpha heuristic thresholds against the mean density of the plain border,
# so it misreads two shapes. These values were measured off a pixel grid and
# confirmed in the browser. Format: name "top right bottom left".
#
# Two frames are deliberately absent from FRAMES.
#
# panel-frame-tall's only ornament is a single top-centre diamond, which
# border-image cannot place.
#
# panel-frame-inset carries a stepped bracket reaching x=72,y=100 on its top two
# corners only. No single slice keeps that bracket intact and also avoids
# stretching its leftover down the vertical edges, which showed as ticks across
# the panel text. It is drawn in CSS instead: see .panel--inset in rmv.css.
# Plain indexed array rather than declare -A: macOS ships bash 3.2, which has
# no associative arrays, and this should run without a Homebrew bash.
OVERRIDES=(
  # The trinity knot's outer lobes are faint, so the heuristic clips them at 61.
  "panel-frame-card=82 82 82 82"
  # Heuristic reads 0: the doubled top rule lifts the baseline above the thin
  # diamond outline. The nested diamond end ornament reaches x=68.
  "header-bar-frame=24 70 24 70"
)

# Echo the override for $1, or nothing if there is not one.
override_for() {
  local entry
  for entry in "${OVERRIDES[@]}"; do
    if [[ "${entry%%=*}" == "$1" ]]; then
      printf '%s' "${entry#*=}"
      return
    fi
  done
}

# Mean alpha per column (axis=x) or per row (axis=y), as whitespace-separated ints.
profile() {
  local img="$1" axis="$2" w h geom
  read -r w h < <(magick identify -format '%w %h\n' "$img")
  [[ "$axis" == x ]] && geom="${w}x1!" || geom="1x${h}!"
  magick "$img" -alpha extract -scale "$geom" -depth 8 txt:- \
    | sed -n 's/.*gray(\([0-9]*\)).*/\1/p'
}

# Last index whose value exceeds the plain-border baseline, i.e. where the
# corner ornament stops. Reads the profile on stdin, so the script comes via -c
# rather than a heredoc (a heredoc would occupy stdin itself).
edge_extent() {
  python3 -c '
import sys
side = sys.argv[1]                # "lead" scans from the start, "trail" from the end
vals = [int(v) for v in sys.stdin.read().split()]
n = len(vals)
if n < 8:
    print(0); raise SystemExit
if side == "trail":
    vals = vals[::-1]
# Baseline = the plain border, sampled mid-edge where no ornament reaches.
mid = vals[n // 3: 2 * n // 3]
baseline = sum(mid) / len(mid) if mid else 0
# Ornament threshold: clearly denser than the plain border, tolerant of noise.
thresh = max(baseline * 1.6, baseline + 6, 4)
last = 0
# Ornaments live at the corners, so only the outer 30% is worth scanning.
for i, v in enumerate(vals[: max(4, int(n * 0.30))]):
    if v > thresh:
        last = i
print(last + 1)
' "$1"
}

printf '/* Generated by tools/measure-border-slices.sh. Do not hand-edit. */\n'
printf ':root {\n'
for f in "${FRAMES[@]}"; do
  img="$IMG_DIR/$f.png"
  if [[ ! -f "$img" ]]; then
    printf '  /* %-20s missing, run tools/slice-nordic-ui.sh */\n' "$f"
    continue
  fi
  read -r w h < <(magick identify -format '%w %h\n' "$img")
  left=$(profile   "$img" x | edge_extent lead)
  right=$(profile  "$img" x | edge_extent trail)
  top=$(profile    "$img" y | edge_extent lead)
  bottom=$(profile "$img" y | edge_extent trail)
  # border-image-slice takes top right bottom left, and cannot exceed the image.
  (( left  + right  < w )) || { left=$((w / 3)); right=$((w / 3)); }
  (( top   + bottom < h )) || { top=$((h / 3)); bottom=$((h / 3)); }
  ov=""
  ov="$(override_for "$f")"
  if [[ -n "$ov" ]]; then
    printf '  --slice-%-22s %s; /* %sx%s  override, measured %s %s %s %s */\n' \
      "$f:" "$ov" "$w" "$h" "$top" "$right" "$bottom" "$left"
  else
    printf '  --slice-%-22s %s %s %s %s; /* %sx%s */\n' \
      "$f:" "$top" "$right" "$bottom" "$left" "$w" "$h"
  fi
done
printf '}\n'
